/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppContentRouteImport } from './routes/app.content'
import { Route as AppJourneyRouteImport } from './routes/app.journey'
import { Route as AppNotesRouteImport } from './routes/app.notes'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppReportCardRouteImport } from './routes/app.report-card'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppWelcomeRouteImport } from './routes/app.welcome'
import { Route as AppAdminAttendanceRouteImport } from './routes/app.admin.attendance'
import { Route as AppAdminContentRouteImport } from './routes/app.admin.content'
import { Route as AppAdminDashboardRouteImport } from './routes/app.admin.dashboard'
import { Route as AppAdminLectureViewsRouteImport } from './routes/app.admin.lecture-views'
import { Route as AppAdminLumiRouteImport } from './routes/app.admin.lumi'
import { Route as AppAdminOfflineTestsRouteImport } from './routes/app.admin.offline-tests'
import { Route as AppAdminProgressRouteImport } from './routes/app.admin.progress'
import { Route as AppAdminRanksRouteImport } from './routes/app.admin.ranks'
import { Route as AppAdminSettingsRouteImport } from './routes/app.admin.settings'
import { Route as AppBuildingLibraryRouteImport } from './routes/app.building.library'
import { Route as AppBuildingMathRouteImport } from './routes/app.building.math'
import { Route as AppBuildingScienceRouteImport } from './routes/app.building.science'
import { Route as AppJourneyIndexRouteImport } from './routes/app.journey.index'
import { Route as AppAdminStudentsIndexRouteImport } from './routes/app.admin.students.index'
import { Route as AppAdminStudentsIdRouteImport } from './routes/app.admin.students.$id'
import { Route as AppJourneyWorldIdIndexRouteImport } from './routes/app.journey.$worldId.index'
import { Route as AppJourneyWorldIdDungeonIdRouteImport } from './routes/app.journey.$worldId.$dungeonId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppContentRoute = AppContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AppRoute,
} as any)
const AppJourneyRoute = AppJourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesRoute = AppNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppReportCardRoute = AppReportCardRouteImport.update({
  id: '/report-card',
  path: '/report-card',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppWelcomeRoute = AppWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAttendanceRoute = AppAdminAttendanceRouteImport.update({
  id: '/admin/attendance',
  path: '/admin/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminContentRoute = AppAdminContentRouteImport.update({
  id: '/admin/content',
  path: '/admin/content',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminDashboardRoute = AppAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminLectureViewsRoute = AppAdminLectureViewsRouteImport.update({
  id: '/admin/lecture-views',
  path: '/admin/lecture-views',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminLumiRoute = AppAdminLumiRouteImport.update({
  id: '/admin/lumi',
  path: '/admin/lumi',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminOfflineTestsRoute = AppAdminOfflineTestsRouteImport.update({
  id: '/admin/offline-tests',
  path: '/admin/offline-tests',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminProgressRoute = AppAdminProgressRouteImport.update({
  id: '/admin/progress',
  path: '/admin/progress',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRanksRoute = AppAdminRanksRouteImport.update({
  id: '/admin/ranks',
  path: '/admin/ranks',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSettingsRoute = AppAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppBuildingLibraryRoute = AppBuildingLibraryRouteImport.update({
  id: '/building/library',
  path: '/building/library',
  getParentRoute: () => AppRoute,
} as any)
const AppBuildingMathRoute = AppBuildingMathRouteImport.update({
  id: '/building/math',
  path: '/building/math',
  getParentRoute: () => AppRoute,
} as any)
const AppBuildingScienceRoute = AppBuildingScienceRouteImport.update({
  id: '/building/science',
  path: '/building/science',
  getParentRoute: () => AppRoute,
} as any)
const AppJourneyIndexRoute = AppJourneyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppJourneyRoute,
} as any)
const AppAdminStudentsIndexRoute = AppAdminStudentsIndexRouteImport.update({
  id: '/admin/students/',
  path: '/admin/students/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminStudentsIdRoute = AppAdminStudentsIdRouteImport.update({
  id: '/admin/students/$id',
  path: '/admin/students/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppJourneyWorldIdIndexRoute = AppJourneyWorldIdIndexRouteImport.update({
  id: '/$worldId/',
  path: '/$worldId/',
  getParentRoute: () => AppJourneyRoute,
} as any)
const AppJourneyWorldIdDungeonIdRoute =
  AppJourneyWorldIdDungeonIdRouteImport.update({
    id: '/$worldId/$dungeonId',
    path: '/$worldId/$dungeonId',
    getParentRoute: () => AppJourneyRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/app/content': typeof AppContentRoute
  '/app/journey': typeof AppJourneyRouteWithChildren
  '/app/notes': typeof AppNotesRoute
  '/app/profile': typeof AppProfileRoute
  '/app/report-card': typeof AppReportCardRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/welcome': typeof AppWelcomeRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/attendance': typeof AppAdminAttendanceRoute
  '/app/admin/content': typeof AppAdminContentRoute
  '/app/admin/dashboard': typeof AppAdminDashboardRoute
  '/app/admin/lecture-views': typeof AppAdminLectureViewsRoute
  '/app/admin/lumi': typeof AppAdminLumiRoute
  '/app/admin/offline-tests': typeof AppAdminOfflineTestsRoute
  '/app/admin/progress': typeof AppAdminProgressRoute
  '/app/admin/ranks': typeof AppAdminRanksRoute
  '/app/admin/settings': typeof AppAdminSettingsRoute
  '/app/building/library': typeof AppBuildingLibraryRoute
  '/app/building/math': typeof AppBuildingMathRoute
  '/app/building/science': typeof AppBuildingScienceRoute
  '/app/journey/': typeof AppJourneyIndexRoute
  '/app/admin/students/$id': typeof AppAdminStudentsIdRoute
  '/app/journey/$worldId/$dungeonId': typeof AppJourneyWorldIdDungeonIdRoute
  '/app/admin/students/': typeof AppAdminStudentsIndexRoute
  '/app/journey/$worldId/': typeof AppJourneyWorldIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/app/content': typeof AppContentRoute
  '/app/notes': typeof AppNotesRoute
  '/app/profile': typeof AppProfileRoute
  '/app/report-card': typeof AppReportCardRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/welcome': typeof AppWelcomeRoute
  '/app': typeof AppIndexRoute
  '/app/admin/attendance': typeof AppAdminAttendanceRoute
  '/app/admin/content': typeof AppAdminContentRoute
  '/app/admin/dashboard': typeof AppAdminDashboardRoute
  '/app/admin/lecture-views': typeof AppAdminLectureViewsRoute
  '/app/admin/lumi': typeof AppAdminLumiRoute
  '/app/admin/offline-tests': typeof AppAdminOfflineTestsRoute
  '/app/admin/progress': typeof AppAdminProgressRoute
  '/app/admin/ranks': typeof AppAdminRanksRoute
  '/app/admin/settings': typeof AppAdminSettingsRoute
  '/app/building/library': typeof AppBuildingLibraryRoute
  '/app/building/math': typeof AppBuildingMathRoute
  '/app/building/science': typeof AppBuildingScienceRoute
  '/app/journey': typeof AppJourneyIndexRoute
  '/app/admin/students/$id': typeof AppAdminStudentsIdRoute
  '/app/journey/$worldId/$dungeonId': typeof AppJourneyWorldIdDungeonIdRoute
  '/app/admin/students': typeof AppAdminStudentsIndexRoute
  '/app/journey/$worldId': typeof AppJourneyWorldIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/app/content': typeof AppContentRoute
  '/app/journey': typeof AppJourneyRouteWithChildren
  '/app/notes': typeof AppNotesRoute
  '/app/profile': typeof AppProfileRoute
  '/app/report-card': typeof AppReportCardRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/welcome': typeof AppWelcomeRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/attendance': typeof AppAdminAttendanceRoute
  '/app/admin/content': typeof AppAdminContentRoute
  '/app/admin/dashboard': typeof AppAdminDashboardRoute
  '/app/admin/lecture-views': typeof AppAdminLectureViewsRoute
  '/app/admin/lumi': typeof AppAdminLumiRoute
  '/app/admin/offline-tests': typeof AppAdminOfflineTestsRoute
  '/app/admin/progress': typeof AppAdminProgressRoute
  '/app/admin/ranks': typeof AppAdminRanksRoute
  '/app/admin/settings': typeof AppAdminSettingsRoute
  '/app/building/library': typeof AppBuildingLibraryRoute
  '/app/building/math': typeof AppBuildingMathRoute
  '/app/building/science': typeof AppBuildingScienceRoute
  '/app/journey/': typeof AppJourneyIndexRoute
  '/app/admin/students/$id': typeof AppAdminStudentsIdRoute
  '/app/journey/$worldId/$dungeonId': typeof AppJourneyWorldIdDungeonIdRoute
  '/app/admin/students/': typeof AppAdminStudentsIndexRoute
  '/app/journey/$worldId/': typeof AppJourneyWorldIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/setup'
    | '/app/content'
    | '/app/journey'
    | '/app/notes'
    | '/app/profile'
    | '/app/report-card'
    | '/app/settings'
    | '/app/welcome'
    | '/app/'
    | '/app/admin/attendance'
    | '/app/admin/content'
    | '/app/admin/dashboard'
    | '/app/admin/lecture-views'
    | '/app/admin/lumi'
    | '/app/admin/offline-tests'
    | '/app/admin/progress'
    | '/app/admin/ranks'
    | '/app/admin/settings'
    | '/app/building/library'
    | '/app/building/math'
    | '/app/building/science'
    | '/app/journey/'
    | '/app/admin/students/$id'
    | '/app/journey/$worldId/$dungeonId'
    | '/app/admin/students/'
    | '/app/journey/$worldId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/setup'
    | '/app/content'
    | '/app/notes'
    | '/app/profile'
    | '/app/report-card'
    | '/app/settings'
    | '/app/welcome'
    | '/app'
    | '/app/admin/attendance'
    | '/app/admin/content'
    | '/app/admin/dashboard'
    | '/app/admin/lecture-views'
    | '/app/admin/lumi'
    | '/app/admin/offline-tests'
    | '/app/admin/progress'
    | '/app/admin/ranks'
    | '/app/admin/settings'
    | '/app/building/library'
    | '/app/building/math'
    | '/app/building/science'
    | '/app/journey'
    | '/app/admin/students/$id'
    | '/app/journey/$worldId/$dungeonId'
    | '/app/admin/students'
    | '/app/journey/$worldId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/setup'
    | '/app/content'
    | '/app/journey'
    | '/app/notes'
    | '/app/profile'
    | '/app/report-card'
    | '/app/settings'
    | '/app/welcome'
    | '/app/'
    | '/app/admin/attendance'
    | '/app/admin/content'
    | '/app/admin/dashboard'
    | '/app/admin/lecture-views'
    | '/app/admin/lumi'
    | '/app/admin/offline-tests'
    | '/app/admin/progress'
    | '/app/admin/ranks'
    | '/app/admin/settings'
    | '/app/building/library'
    | '/app/building/math'
    | '/app/building/science'
    | '/app/journey/'
    | '/app/admin/students/$id'
    | '/app/journey/$worldId/$dungeonId'
    | '/app/admin/students/'
    | '/app/journey/$worldId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/content': {
      id: '/app/content'
      path: '/content'
      fullPath: '/app/content'
      preLoaderRoute: typeof AppContentRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/journey': {
      id: '/app/journey'
      path: '/journey'
      fullPath: '/app/journey'
      preLoaderRoute: typeof AppJourneyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notes': {
      id: '/app/notes'
      path: '/notes'
      fullPath: '/app/notes'
      preLoaderRoute: typeof AppNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/report-card': {
      id: '/app/report-card'
      path: '/report-card'
      fullPath: '/app/report-card'
      preLoaderRoute: typeof AppReportCardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/welcome': {
      id: '/app/welcome'
      path: '/welcome'
      fullPath: '/app/welcome'
      preLoaderRoute: typeof AppWelcomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/attendance': {
      id: '/app/admin/attendance'
      path: '/admin/attendance'
      fullPath: '/app/admin/attendance'
      preLoaderRoute: typeof AppAdminAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/content': {
      id: '/app/admin/content'
      path: '/admin/content'
      fullPath: '/app/admin/content'
      preLoaderRoute: typeof AppAdminContentRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/dashboard': {
      id: '/app/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/app/admin/dashboard'
      preLoaderRoute: typeof AppAdminDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/lecture-views': {
      id: '/app/admin/lecture-views'
      path: '/admin/lecture-views'
      fullPath: '/app/admin/lecture-views'
      preLoaderRoute: typeof AppAdminLectureViewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/lumi': {
      id: '/app/admin/lumi'
      path: '/admin/lumi'
      fullPath: '/app/admin/lumi'
      preLoaderRoute: typeof AppAdminLumiRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/offline-tests': {
      id: '/app/admin/offline-tests'
      path: '/admin/offline-tests'
      fullPath: '/app/admin/offline-tests'
      preLoaderRoute: typeof AppAdminOfflineTestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/progress': {
      id: '/app/admin/progress'
      path: '/admin/progress'
      fullPath: '/app/admin/progress'
      preLoaderRoute: typeof AppAdminProgressRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/ranks': {
      id: '/app/admin/ranks'
      path: '/admin/ranks'
      fullPath: '/app/admin/ranks'
      preLoaderRoute: typeof AppAdminRanksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/settings': {
      id: '/app/admin/settings'
      path: '/admin/settings'
      fullPath: '/app/admin/settings'
      preLoaderRoute: typeof AppAdminSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/building/library': {
      id: '/app/building/library'
      path: '/building/library'
      fullPath: '/app/building/library'
      preLoaderRoute: typeof AppBuildingLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/building/math': {
      id: '/app/building/math'
      path: '/building/math'
      fullPath: '/app/building/math'
      preLoaderRoute: typeof AppBuildingMathRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/building/science': {
      id: '/app/building/science'
      path: '/building/science'
      fullPath: '/app/building/science'
      preLoaderRoute: typeof AppBuildingScienceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/journey/': {
      id: '/app/journey/'
      path: '/'
      fullPath: '/app/journey/'
      preLoaderRoute: typeof AppJourneyIndexRouteImport
      parentRoute: typeof AppJourneyRoute
    }
    '/app/admin/students/': {
      id: '/app/admin/students/'
      path: '/admin/students'
      fullPath: '/app/admin/students/'
      preLoaderRoute: typeof AppAdminStudentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/students/$id': {
      id: '/app/admin/students/$id'
      path: '/admin/students/$id'
      fullPath: '/app/admin/students/$id'
      preLoaderRoute: typeof AppAdminStudentsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/journey/$worldId/': {
      id: '/app/journey/$worldId/'
      path: '/$worldId'
      fullPath: '/app/journey/$worldId/'
      preLoaderRoute: typeof AppJourneyWorldIdIndexRouteImport
      parentRoute: typeof AppJourneyRoute
    }
    '/app/journey/$worldId/$dungeonId': {
      id: '/app/journey/$worldId/$dungeonId'
      path: '/$worldId/$dungeonId'
      fullPath: '/app/journey/$worldId/$dungeonId'
      preLoaderRoute: typeof AppJourneyWorldIdDungeonIdRouteImport
      parentRoute: typeof AppJourneyRoute
    }
  }
}

interface AppJourneyRouteChildren {
  AppJourneyIndexRoute: typeof AppJourneyIndexRoute
  AppJourneyWorldIdDungeonIdRoute: typeof AppJourneyWorldIdDungeonIdRoute
  AppJourneyWorldIdIndexRoute: typeof AppJourneyWorldIdIndexRoute
}

const AppJourneyRouteChildren: AppJourneyRouteChildren = {
  AppJourneyIndexRoute: AppJourneyIndexRoute,
  AppJourneyWorldIdDungeonIdRoute: AppJourneyWorldIdDungeonIdRoute,
  AppJourneyWorldIdIndexRoute: AppJourneyWorldIdIndexRoute,
}

const AppJourneyRouteWithChildren = AppJourneyRoute._addFileChildren(
  AppJourneyRouteChildren,
)

interface AppRouteChildren {
  AppContentRoute: typeof AppContentRoute
  AppJourneyRoute: typeof AppJourneyRouteWithChildren
  AppNotesRoute: typeof AppNotesRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReportCardRoute: typeof AppReportCardRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppWelcomeRoute: typeof AppWelcomeRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminAttendanceRoute: typeof AppAdminAttendanceRoute
  AppAdminContentRoute: typeof AppAdminContentRoute
  AppAdminDashboardRoute: typeof AppAdminDashboardRoute
  AppAdminLectureViewsRoute: typeof AppAdminLectureViewsRoute
  AppAdminLumiRoute: typeof AppAdminLumiRoute
  AppAdminOfflineTestsRoute: typeof AppAdminOfflineTestsRoute
  AppAdminProgressRoute: typeof AppAdminProgressRoute
  AppAdminRanksRoute: typeof AppAdminRanksRoute
  AppAdminSettingsRoute: typeof AppAdminSettingsRoute
  AppBuildingLibraryRoute: typeof AppBuildingLibraryRoute
  AppBuildingMathRoute: typeof AppBuildingMathRoute
  AppBuildingScienceRoute: typeof AppBuildingScienceRoute
  AppAdminStudentsIdRoute: typeof AppAdminStudentsIdRoute
  AppAdminStudentsIndexRoute: typeof AppAdminStudentsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppContentRoute: AppContentRoute,
  AppJourneyRoute: AppJourneyRouteWithChildren,
  AppNotesRoute: AppNotesRoute,
  AppProfileRoute: AppProfileRoute,
  AppReportCardRoute: AppReportCardRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppWelcomeRoute: AppWelcomeRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminAttendanceRoute: AppAdminAttendanceRoute,
  AppAdminContentRoute: AppAdminContentRoute,
  AppAdminDashboardRoute: AppAdminDashboardRoute,
  AppAdminLectureViewsRoute: AppAdminLectureViewsRoute,
  AppAdminLumiRoute: AppAdminLumiRoute,
  AppAdminOfflineTestsRoute: AppAdminOfflineTestsRoute,
  AppAdminProgressRoute: AppAdminProgressRoute,
  AppAdminRanksRoute: AppAdminRanksRoute,
  AppAdminSettingsRoute: AppAdminSettingsRoute,
  AppBuildingLibraryRoute: AppBuildingLibraryRoute,
  AppBuildingMathRoute: AppBuildingMathRoute,
  AppBuildingScienceRoute: AppBuildingScienceRoute,
  AppAdminStudentsIdRoute: AppAdminStudentsIdRoute,
  AppAdminStudentsIndexRoute: AppAdminStudentsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
