/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppWelcomeRouteImport } from './routes/app.welcome'
import { Route as AppTestsRouteImport } from './routes/app.tests'
import { Route as AppTalentsRouteImport } from './routes/app.talents'
import { Route as AppStudentsRouteImport } from './routes/app.students'
import { Route as AppSpinRouteImport } from './routes/app.spin'
import { Route as AppShopRouteImport } from './routes/app.shop'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppResultsRouteImport } from './routes/app.results'
import { Route as AppReportCardRouteImport } from './routes/app.report-card'
import { Route as AppPvpRouteImport } from './routes/app.pvp'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppPetsRouteImport } from './routes/app.pets'
import { Route as AppPassesRouteImport } from './routes/app.passes'
import { Route as AppNotesRouteImport } from './routes/app.notes'
import { Route as AppLeaderboardRouteImport } from './routes/app.leaderboard'
import { Route as AppJourneyRouteImport } from './routes/app.journey'
import { Route as AppInventoryRouteImport } from './routes/app.inventory'
import { Route as AppGuidebookRouteImport } from './routes/app.guidebook'
import { Route as AppContentRouteImport } from './routes/app.content'
import { Route as AppCollectionRouteImport } from './routes/app.collection'
import { Route as AppCoinsRouteImport } from './routes/app.coins'
import { Route as AppAttendanceRouteImport } from './routes/app.attendance'
import { Route as AppAnnouncementsRouteImport } from './routes/app.announcements'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppAchievementsRouteImport } from './routes/app.achievements'
import { Route as AppPvpIndexRouteImport } from './routes/app.pvp.index'
import { Route as AppJourneyIndexRouteImport } from './routes/app.journey.index'
import { Route as AppTestsTestIdRouteImport } from './routes/app.tests.$testId'
import { Route as AppBuildingMathRouteImport } from './routes/app.building.math'
import { Route as AppAnalyticsTestIdRouteImport } from './routes/app.analytics.$testId'
import { Route as AppAdminTalentsRouteImport } from './routes/app.admin.talents'
import { Route as AppAdminSpinRouteImport } from './routes/app.admin.spin'
import { Route as AppAdminSettingsRouteImport } from './routes/app.admin.settings'
import { Route as AppAdminQuizImportRouteImport } from './routes/app.admin.quiz-import'
import { Route as AppAdminPassesRouteImport } from './routes/app.admin.passes'
import { Route as AppAdminOfflineTestsRouteImport } from './routes/app.admin.offline-tests'
import { Route as AppAdminLumiRouteImport } from './routes/app.admin.lumi'
import { Route as AppAdminLectureViewsRouteImport } from './routes/app.admin.lecture-views'
import { Route as AppAdminLectureQuizzesRouteImport } from './routes/app.admin.lecture-quizzes'
import { Route as AppAdminGamificationRouteImport } from './routes/app.admin.gamification'
import { Route as AppAdminDashboardRouteImport } from './routes/app.admin.dashboard'
import { Route as AppAdminContentRouteImport } from './routes/app.admin.content'
import { Route as AppAdminCadetsRouteImport } from './routes/app.admin.cadets'
import { Route as AppAdminAttendanceRouteImport } from './routes/app.admin.attendance'
import { Route as AppAdminAssessmentRouteImport } from './routes/app.admin.assessment'
import { Route as AppJourneyWorldIdIndexRouteImport } from './routes/app.journey.$worldId.index'
import { Route as AppPvpDuelIdRouteImport } from './routes/app.pvp.duel.$id'
import { Route as AppPvpBrIdRouteImport } from './routes/app.pvp.br.$id'
import { Route as AppJourneyWorldIdDungeonIdRouteImport } from './routes/app.journey.$worldId.$dungeonId'
import { Route as AppAdminStudentsIdRouteImport } from './routes/app.admin.students.$id'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWelcomeRoute = AppWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AppRoute,
} as any)
const AppTestsRoute = AppTestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => AppRoute,
} as any)
const AppTalentsRoute = AppTalentsRouteImport.update({
  id: '/talents',
  path: '/talents',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsRoute = AppStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AppRoute,
} as any)
const AppSpinRoute = AppSpinRouteImport.update({
  id: '/spin',
  path: '/spin',
  getParentRoute: () => AppRoute,
} as any)
const AppShopRoute = AppShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppResultsRoute = AppResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AppRoute,
} as any)
const AppReportCardRoute = AppReportCardRouteImport.update({
  id: '/report-card',
  path: '/report-card',
  getParentRoute: () => AppRoute,
} as any)
const AppPvpRoute = AppPvpRouteImport.update({
  id: '/pvp',
  path: '/pvp',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPetsRoute = AppPetsRouteImport.update({
  id: '/pets',
  path: '/pets',
  getParentRoute: () => AppRoute,
} as any)
const AppPassesRoute = AppPassesRouteImport.update({
  id: '/passes',
  path: '/passes',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesRoute = AppNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardRoute = AppLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppJourneyRoute = AppJourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppGuidebookRoute = AppGuidebookRouteImport.update({
  id: '/guidebook',
  path: '/guidebook',
  getParentRoute: () => AppRoute,
} as any)
const AppContentRoute = AppContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AppRoute,
} as any)
const AppCollectionRoute = AppCollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => AppRoute,
} as any)
const AppCoinsRoute = AppCoinsRouteImport.update({
  id: '/coins',
  path: '/coins',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppAnnouncementsRoute = AppAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAchievementsRoute = AppAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => AppRoute,
} as any)
const AppPvpIndexRoute = AppPvpIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPvpRoute,
} as any)
const AppJourneyIndexRoute = AppJourneyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppJourneyRoute,
} as any)
const AppTestsTestIdRoute = AppTestsTestIdRouteImport.update({
  id: '/$testId',
  path: '/$testId',
  getParentRoute: () => AppTestsRoute,
} as any)
const AppBuildingMathRoute = AppBuildingMathRouteImport.update({
  id: '/building/math',
  path: '/building/math',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsTestIdRoute = AppAnalyticsTestIdRouteImport.update({
  id: '/$testId',
  path: '/$testId',
  getParentRoute: () => AppAnalyticsRoute,
} as any)
const AppAdminTalentsRoute = AppAdminTalentsRouteImport.update({
  id: '/admin/talents',
  path: '/admin/talents',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSpinRoute = AppAdminSpinRouteImport.update({
  id: '/admin/spin',
  path: '/admin/spin',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSettingsRoute = AppAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminQuizImportRoute = AppAdminQuizImportRouteImport.update({
  id: '/admin/quiz-import',
  path: '/admin/quiz-import',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminPassesRoute = AppAdminPassesRouteImport.update({
  id: '/admin/passes',
  path: '/admin/passes',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminOfflineTestsRoute = AppAdminOfflineTestsRouteImport.update({
  id: '/admin/offline-tests',
  path: '/admin/offline-tests',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminLumiRoute = AppAdminLumiRouteImport.update({
  id: '/admin/lumi',
  path: '/admin/lumi',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminLectureViewsRoute = AppAdminLectureViewsRouteImport.update({
  id: '/admin/lecture-views',
  path: '/admin/lecture-views',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminLectureQuizzesRoute = AppAdminLectureQuizzesRouteImport.update({
  id: '/admin/lecture-quizzes',
  path: '/admin/lecture-quizzes',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminGamificationRoute = AppAdminGamificationRouteImport.update({
  id: '/admin/gamification',
  path: '/admin/gamification',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminDashboardRoute = AppAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminContentRoute = AppAdminContentRouteImport.update({
  id: '/admin/content',
  path: '/admin/content',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminCadetsRoute = AppAdminCadetsRouteImport.update({
  id: '/admin/cadets',
  path: '/admin/cadets',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAttendanceRoute = AppAdminAttendanceRouteImport.update({
  id: '/admin/attendance',
  path: '/admin/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAssessmentRoute = AppAdminAssessmentRouteImport.update({
  id: '/admin/assessment',
  path: '/admin/assessment',
  getParentRoute: () => AppRoute,
} as any)
const AppJourneyWorldIdIndexRoute = AppJourneyWorldIdIndexRouteImport.update({
  id: '/$worldId/',
  path: '/$worldId/',
  getParentRoute: () => AppJourneyRoute,
} as any)
const AppPvpDuelIdRoute = AppPvpDuelIdRouteImport.update({
  id: '/duel/$id',
  path: '/duel/$id',
  getParentRoute: () => AppPvpRoute,
} as any)
const AppPvpBrIdRoute = AppPvpBrIdRouteImport.update({
  id: '/br/$id',
  path: '/br/$id',
  getParentRoute: () => AppPvpRoute,
} as any)
const AppJourneyWorldIdDungeonIdRoute =
  AppJourneyWorldIdDungeonIdRouteImport.update({
    id: '/$worldId/$dungeonId',
    path: '/$worldId/$dungeonId',
    getParentRoute: () => AppJourneyRoute,
  } as any)
const AppAdminStudentsIdRoute = AppAdminStudentsIdRouteImport.update({
  id: '/admin/students/$id',
  path: '/admin/students/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/app/achievements': typeof AppAchievementsRoute
  '/app/analytics': typeof AppAnalyticsRouteWithChildren
  '/app/announcements': typeof AppAnnouncementsRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/coins': typeof AppCoinsRoute
  '/app/collection': typeof AppCollectionRoute
  '/app/content': typeof AppContentRoute
  '/app/guidebook': typeof AppGuidebookRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/journey': typeof AppJourneyRouteWithChildren
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/notes': typeof AppNotesRoute
  '/app/passes': typeof AppPassesRoute
  '/app/pets': typeof AppPetsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/pvp': typeof AppPvpRouteWithChildren
  '/app/report-card': typeof AppReportCardRoute
  '/app/results': typeof AppResultsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/shop': typeof AppShopRoute
  '/app/spin': typeof AppSpinRoute
  '/app/students': typeof AppStudentsRoute
  '/app/talents': typeof AppTalentsRoute
  '/app/tests': typeof AppTestsRouteWithChildren
  '/app/welcome': typeof AppWelcomeRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/assessment': typeof AppAdminAssessmentRoute
  '/app/admin/attendance': typeof AppAdminAttendanceRoute
  '/app/admin/cadets': typeof AppAdminCadetsRoute
  '/app/admin/content': typeof AppAdminContentRoute
  '/app/admin/dashboard': typeof AppAdminDashboardRoute
  '/app/admin/gamification': typeof AppAdminGamificationRoute
  '/app/admin/lecture-quizzes': typeof AppAdminLectureQuizzesRoute
  '/app/admin/lecture-views': typeof AppAdminLectureViewsRoute
  '/app/admin/lumi': typeof AppAdminLumiRoute
  '/app/admin/offline-tests': typeof AppAdminOfflineTestsRoute
  '/app/admin/passes': typeof AppAdminPassesRoute
  '/app/admin/quiz-import': typeof AppAdminQuizImportRoute
  '/app/admin/settings': typeof AppAdminSettingsRoute
  '/app/admin/spin': typeof AppAdminSpinRoute
  '/app/admin/talents': typeof AppAdminTalentsRoute
  '/app/analytics/$testId': typeof AppAnalyticsTestIdRoute
  '/app/building/math': typeof AppBuildingMathRoute
  '/app/tests/$testId': typeof AppTestsTestIdRoute
  '/app/journey/': typeof AppJourneyIndexRoute
  '/app/pvp/': typeof AppPvpIndexRoute
  '/app/admin/students/$id': typeof AppAdminStudentsIdRoute
  '/app/journey/$worldId/$dungeonId': typeof AppJourneyWorldIdDungeonIdRoute
  '/app/pvp/br/$id': typeof AppPvpBrIdRoute
  '/app/pvp/duel/$id': typeof AppPvpDuelIdRoute
  '/app/journey/$worldId/': typeof AppJourneyWorldIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/app/achievements': typeof AppAchievementsRoute
  '/app/analytics': typeof AppAnalyticsRouteWithChildren
  '/app/announcements': typeof AppAnnouncementsRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/coins': typeof AppCoinsRoute
  '/app/collection': typeof AppCollectionRoute
  '/app/content': typeof AppContentRoute
  '/app/guidebook': typeof AppGuidebookRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/notes': typeof AppNotesRoute
  '/app/passes': typeof AppPassesRoute
  '/app/pets': typeof AppPetsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/report-card': typeof AppReportCardRoute
  '/app/results': typeof AppResultsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/shop': typeof AppShopRoute
  '/app/spin': typeof AppSpinRoute
  '/app/students': typeof AppStudentsRoute
  '/app/talents': typeof AppTalentsRoute
  '/app/tests': typeof AppTestsRouteWithChildren
  '/app/welcome': typeof AppWelcomeRoute
  '/app': typeof AppIndexRoute
  '/app/admin/assessment': typeof AppAdminAssessmentRoute
  '/app/admin/attendance': typeof AppAdminAttendanceRoute
  '/app/admin/cadets': typeof AppAdminCadetsRoute
  '/app/admin/content': typeof AppAdminContentRoute
  '/app/admin/dashboard': typeof AppAdminDashboardRoute
  '/app/admin/gamification': typeof AppAdminGamificationRoute
  '/app/admin/lecture-quizzes': typeof AppAdminLectureQuizzesRoute
  '/app/admin/lecture-views': typeof AppAdminLectureViewsRoute
  '/app/admin/lumi': typeof AppAdminLumiRoute
  '/app/admin/offline-tests': typeof AppAdminOfflineTestsRoute
  '/app/admin/passes': typeof AppAdminPassesRoute
  '/app/admin/quiz-import': typeof AppAdminQuizImportRoute
  '/app/admin/settings': typeof AppAdminSettingsRoute
  '/app/admin/spin': typeof AppAdminSpinRoute
  '/app/admin/talents': typeof AppAdminTalentsRoute
  '/app/analytics/$testId': typeof AppAnalyticsTestIdRoute
  '/app/building/math': typeof AppBuildingMathRoute
  '/app/tests/$testId': typeof AppTestsTestIdRoute
  '/app/journey': typeof AppJourneyIndexRoute
  '/app/pvp': typeof AppPvpIndexRoute
  '/app/admin/students/$id': typeof AppAdminStudentsIdRoute
  '/app/journey/$worldId/$dungeonId': typeof AppJourneyWorldIdDungeonIdRoute
  '/app/pvp/br/$id': typeof AppPvpBrIdRoute
  '/app/pvp/duel/$id': typeof AppPvpDuelIdRoute
  '/app/journey/$worldId': typeof AppJourneyWorldIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/app/achievements': typeof AppAchievementsRoute
  '/app/analytics': typeof AppAnalyticsRouteWithChildren
  '/app/announcements': typeof AppAnnouncementsRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/coins': typeof AppCoinsRoute
  '/app/collection': typeof AppCollectionRoute
  '/app/content': typeof AppContentRoute
  '/app/guidebook': typeof AppGuidebookRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/journey': typeof AppJourneyRouteWithChildren
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/notes': typeof AppNotesRoute
  '/app/passes': typeof AppPassesRoute
  '/app/pets': typeof AppPetsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/pvp': typeof AppPvpRouteWithChildren
  '/app/report-card': typeof AppReportCardRoute
  '/app/results': typeof AppResultsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/shop': typeof AppShopRoute
  '/app/spin': typeof AppSpinRoute
  '/app/students': typeof AppStudentsRoute
  '/app/talents': typeof AppTalentsRoute
  '/app/tests': typeof AppTestsRouteWithChildren
  '/app/welcome': typeof AppWelcomeRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/assessment': typeof AppAdminAssessmentRoute
  '/app/admin/attendance': typeof AppAdminAttendanceRoute
  '/app/admin/cadets': typeof AppAdminCadetsRoute
  '/app/admin/content': typeof AppAdminContentRoute
  '/app/admin/dashboard': typeof AppAdminDashboardRoute
  '/app/admin/gamification': typeof AppAdminGamificationRoute
  '/app/admin/lecture-quizzes': typeof AppAdminLectureQuizzesRoute
  '/app/admin/lecture-views': typeof AppAdminLectureViewsRoute
  '/app/admin/lumi': typeof AppAdminLumiRoute
  '/app/admin/offline-tests': typeof AppAdminOfflineTestsRoute
  '/app/admin/passes': typeof AppAdminPassesRoute
  '/app/admin/quiz-import': typeof AppAdminQuizImportRoute
  '/app/admin/settings': typeof AppAdminSettingsRoute
  '/app/admin/spin': typeof AppAdminSpinRoute
  '/app/admin/talents': typeof AppAdminTalentsRoute
  '/app/analytics/$testId': typeof AppAnalyticsTestIdRoute
  '/app/building/math': typeof AppBuildingMathRoute
  '/app/tests/$testId': typeof AppTestsTestIdRoute
  '/app/journey/': typeof AppJourneyIndexRoute
  '/app/pvp/': typeof AppPvpIndexRoute
  '/app/admin/students/$id': typeof AppAdminStudentsIdRoute
  '/app/journey/$worldId/$dungeonId': typeof AppJourneyWorldIdDungeonIdRoute
  '/app/pvp/br/$id': typeof AppPvpBrIdRoute
  '/app/pvp/duel/$id': typeof AppPvpDuelIdRoute
  '/app/journey/$worldId/': typeof AppJourneyWorldIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/setup'
    | '/app/achievements'
    | '/app/analytics'
    | '/app/announcements'
    | '/app/attendance'
    | '/app/coins'
    | '/app/collection'
    | '/app/content'
    | '/app/guidebook'
    | '/app/inventory'
    | '/app/journey'
    | '/app/leaderboard'
    | '/app/notes'
    | '/app/passes'
    | '/app/pets'
    | '/app/profile'
    | '/app/pvp'
    | '/app/report-card'
    | '/app/results'
    | '/app/settings'
    | '/app/shop'
    | '/app/spin'
    | '/app/students'
    | '/app/talents'
    | '/app/tests'
    | '/app/welcome'
    | '/app/'
    | '/app/admin/assessment'
    | '/app/admin/attendance'
    | '/app/admin/cadets'
    | '/app/admin/content'
    | '/app/admin/dashboard'
    | '/app/admin/gamification'
    | '/app/admin/lecture-quizzes'
    | '/app/admin/lecture-views'
    | '/app/admin/lumi'
    | '/app/admin/offline-tests'
    | '/app/admin/passes'
    | '/app/admin/quiz-import'
    | '/app/admin/settings'
    | '/app/admin/spin'
    | '/app/admin/talents'
    | '/app/analytics/$testId'
    | '/app/building/math'
    | '/app/tests/$testId'
    | '/app/journey/'
    | '/app/pvp/'
    | '/app/admin/students/$id'
    | '/app/journey/$worldId/$dungeonId'
    | '/app/pvp/br/$id'
    | '/app/pvp/duel/$id'
    | '/app/journey/$worldId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/setup'
    | '/app/achievements'
    | '/app/analytics'
    | '/app/announcements'
    | '/app/attendance'
    | '/app/coins'
    | '/app/collection'
    | '/app/content'
    | '/app/guidebook'
    | '/app/inventory'
    | '/app/leaderboard'
    | '/app/notes'
    | '/app/passes'
    | '/app/pets'
    | '/app/profile'
    | '/app/report-card'
    | '/app/results'
    | '/app/settings'
    | '/app/shop'
    | '/app/spin'
    | '/app/students'
    | '/app/talents'
    | '/app/tests'
    | '/app/welcome'
    | '/app'
    | '/app/admin/assessment'
    | '/app/admin/attendance'
    | '/app/admin/cadets'
    | '/app/admin/content'
    | '/app/admin/dashboard'
    | '/app/admin/gamification'
    | '/app/admin/lecture-quizzes'
    | '/app/admin/lecture-views'
    | '/app/admin/lumi'
    | '/app/admin/offline-tests'
    | '/app/admin/passes'
    | '/app/admin/quiz-import'
    | '/app/admin/settings'
    | '/app/admin/spin'
    | '/app/admin/talents'
    | '/app/analytics/$testId'
    | '/app/building/math'
    | '/app/tests/$testId'
    | '/app/journey'
    | '/app/pvp'
    | '/app/admin/students/$id'
    | '/app/journey/$worldId/$dungeonId'
    | '/app/pvp/br/$id'
    | '/app/pvp/duel/$id'
    | '/app/journey/$worldId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/setup'
    | '/app/achievements'
    | '/app/analytics'
    | '/app/announcements'
    | '/app/attendance'
    | '/app/coins'
    | '/app/collection'
    | '/app/content'
    | '/app/guidebook'
    | '/app/inventory'
    | '/app/journey'
    | '/app/leaderboard'
    | '/app/notes'
    | '/app/passes'
    | '/app/pets'
    | '/app/profile'
    | '/app/pvp'
    | '/app/report-card'
    | '/app/results'
    | '/app/settings'
    | '/app/shop'
    | '/app/spin'
    | '/app/students'
    | '/app/talents'
    | '/app/tests'
    | '/app/welcome'
    | '/app/'
    | '/app/admin/assessment'
    | '/app/admin/attendance'
    | '/app/admin/cadets'
    | '/app/admin/content'
    | '/app/admin/dashboard'
    | '/app/admin/gamification'
    | '/app/admin/lecture-quizzes'
    | '/app/admin/lecture-views'
    | '/app/admin/lumi'
    | '/app/admin/offline-tests'
    | '/app/admin/passes'
    | '/app/admin/quiz-import'
    | '/app/admin/settings'
    | '/app/admin/spin'
    | '/app/admin/talents'
    | '/app/analytics/$testId'
    | '/app/building/math'
    | '/app/tests/$testId'
    | '/app/journey/'
    | '/app/pvp/'
    | '/app/admin/students/$id'
    | '/app/journey/$worldId/$dungeonId'
    | '/app/pvp/br/$id'
    | '/app/pvp/duel/$id'
    | '/app/journey/$worldId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/welcome': {
      id: '/app/welcome'
      path: '/welcome'
      fullPath: '/app/welcome'
      preLoaderRoute: typeof AppWelcomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tests': {
      id: '/app/tests'
      path: '/tests'
      fullPath: '/app/tests'
      preLoaderRoute: typeof AppTestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/talents': {
      id: '/app/talents'
      path: '/talents'
      fullPath: '/app/talents'
      preLoaderRoute: typeof AppTalentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/students': {
      id: '/app/students'
      path: '/students'
      fullPath: '/app/students'
      preLoaderRoute: typeof AppStudentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/spin': {
      id: '/app/spin'
      path: '/spin'
      fullPath: '/app/spin'
      preLoaderRoute: typeof AppSpinRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/shop': {
      id: '/app/shop'
      path: '/shop'
      fullPath: '/app/shop'
      preLoaderRoute: typeof AppShopRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/results': {
      id: '/app/results'
      path: '/results'
      fullPath: '/app/results'
      preLoaderRoute: typeof AppResultsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/report-card': {
      id: '/app/report-card'
      path: '/report-card'
      fullPath: '/app/report-card'
      preLoaderRoute: typeof AppReportCardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pvp': {
      id: '/app/pvp'
      path: '/pvp'
      fullPath: '/app/pvp'
      preLoaderRoute: typeof AppPvpRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pets': {
      id: '/app/pets'
      path: '/pets'
      fullPath: '/app/pets'
      preLoaderRoute: typeof AppPetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/passes': {
      id: '/app/passes'
      path: '/passes'
      fullPath: '/app/passes'
      preLoaderRoute: typeof AppPassesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notes': {
      id: '/app/notes'
      path: '/notes'
      fullPath: '/app/notes'
      preLoaderRoute: typeof AppNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leaderboard': {
      id: '/app/leaderboard'
      path: '/leaderboard'
      fullPath: '/app/leaderboard'
      preLoaderRoute: typeof AppLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/journey': {
      id: '/app/journey'
      path: '/journey'
      fullPath: '/app/journey'
      preLoaderRoute: typeof AppJourneyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inventory': {
      id: '/app/inventory'
      path: '/inventory'
      fullPath: '/app/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/guidebook': {
      id: '/app/guidebook'
      path: '/guidebook'
      fullPath: '/app/guidebook'
      preLoaderRoute: typeof AppGuidebookRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/content': {
      id: '/app/content'
      path: '/content'
      fullPath: '/app/content'
      preLoaderRoute: typeof AppContentRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/collection': {
      id: '/app/collection'
      path: '/collection'
      fullPath: '/app/collection'
      preLoaderRoute: typeof AppCollectionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/coins': {
      id: '/app/coins'
      path: '/coins'
      fullPath: '/app/coins'
      preLoaderRoute: typeof AppCoinsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/attendance': {
      id: '/app/attendance'
      path: '/attendance'
      fullPath: '/app/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/announcements': {
      id: '/app/announcements'
      path: '/announcements'
      fullPath: '/app/announcements'
      preLoaderRoute: typeof AppAnnouncementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/achievements': {
      id: '/app/achievements'
      path: '/achievements'
      fullPath: '/app/achievements'
      preLoaderRoute: typeof AppAchievementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pvp/': {
      id: '/app/pvp/'
      path: '/'
      fullPath: '/app/pvp/'
      preLoaderRoute: typeof AppPvpIndexRouteImport
      parentRoute: typeof AppPvpRoute
    }
    '/app/journey/': {
      id: '/app/journey/'
      path: '/'
      fullPath: '/app/journey/'
      preLoaderRoute: typeof AppJourneyIndexRouteImport
      parentRoute: typeof AppJourneyRoute
    }
    '/app/tests/$testId': {
      id: '/app/tests/$testId'
      path: '/$testId'
      fullPath: '/app/tests/$testId'
      preLoaderRoute: typeof AppTestsTestIdRouteImport
      parentRoute: typeof AppTestsRoute
    }
    '/app/building/math': {
      id: '/app/building/math'
      path: '/building/math'
      fullPath: '/app/building/math'
      preLoaderRoute: typeof AppBuildingMathRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics/$testId': {
      id: '/app/analytics/$testId'
      path: '/$testId'
      fullPath: '/app/analytics/$testId'
      preLoaderRoute: typeof AppAnalyticsTestIdRouteImport
      parentRoute: typeof AppAnalyticsRoute
    }
    '/app/admin/talents': {
      id: '/app/admin/talents'
      path: '/admin/talents'
      fullPath: '/app/admin/talents'
      preLoaderRoute: typeof AppAdminTalentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/spin': {
      id: '/app/admin/spin'
      path: '/admin/spin'
      fullPath: '/app/admin/spin'
      preLoaderRoute: typeof AppAdminSpinRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/settings': {
      id: '/app/admin/settings'
      path: '/admin/settings'
      fullPath: '/app/admin/settings'
      preLoaderRoute: typeof AppAdminSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/quiz-import': {
      id: '/app/admin/quiz-import'
      path: '/admin/quiz-import'
      fullPath: '/app/admin/quiz-import'
      preLoaderRoute: typeof AppAdminQuizImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/passes': {
      id: '/app/admin/passes'
      path: '/admin/passes'
      fullPath: '/app/admin/passes'
      preLoaderRoute: typeof AppAdminPassesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/offline-tests': {
      id: '/app/admin/offline-tests'
      path: '/admin/offline-tests'
      fullPath: '/app/admin/offline-tests'
      preLoaderRoute: typeof AppAdminOfflineTestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/lumi': {
      id: '/app/admin/lumi'
      path: '/admin/lumi'
      fullPath: '/app/admin/lumi'
      preLoaderRoute: typeof AppAdminLumiRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/lecture-views': {
      id: '/app/admin/lecture-views'
      path: '/admin/lecture-views'
      fullPath: '/app/admin/lecture-views'
      preLoaderRoute: typeof AppAdminLectureViewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/lecture-quizzes': {
      id: '/app/admin/lecture-quizzes'
      path: '/admin/lecture-quizzes'
      fullPath: '/app/admin/lecture-quizzes'
      preLoaderRoute: typeof AppAdminLectureQuizzesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/gamification': {
      id: '/app/admin/gamification'
      path: '/admin/gamification'
      fullPath: '/app/admin/gamification'
      preLoaderRoute: typeof AppAdminGamificationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/dashboard': {
      id: '/app/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/app/admin/dashboard'
      preLoaderRoute: typeof AppAdminDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/content': {
      id: '/app/admin/content'
      path: '/admin/content'
      fullPath: '/app/admin/content'
      preLoaderRoute: typeof AppAdminContentRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/cadets': {
      id: '/app/admin/cadets'
      path: '/admin/cadets'
      fullPath: '/app/admin/cadets'
      preLoaderRoute: typeof AppAdminCadetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/attendance': {
      id: '/app/admin/attendance'
      path: '/admin/attendance'
      fullPath: '/app/admin/attendance'
      preLoaderRoute: typeof AppAdminAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/assessment': {
      id: '/app/admin/assessment'
      path: '/admin/assessment'
      fullPath: '/app/admin/assessment'
      preLoaderRoute: typeof AppAdminAssessmentRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/journey/$worldId/': {
      id: '/app/journey/$worldId/'
      path: '/$worldId'
      fullPath: '/app/journey/$worldId/'
      preLoaderRoute: typeof AppJourneyWorldIdIndexRouteImport
      parentRoute: typeof AppJourneyRoute
    }
    '/app/pvp/duel/$id': {
      id: '/app/pvp/duel/$id'
      path: '/duel/$id'
      fullPath: '/app/pvp/duel/$id'
      preLoaderRoute: typeof AppPvpDuelIdRouteImport
      parentRoute: typeof AppPvpRoute
    }
    '/app/pvp/br/$id': {
      id: '/app/pvp/br/$id'
      path: '/br/$id'
      fullPath: '/app/pvp/br/$id'
      preLoaderRoute: typeof AppPvpBrIdRouteImport
      parentRoute: typeof AppPvpRoute
    }
    '/app/journey/$worldId/$dungeonId': {
      id: '/app/journey/$worldId/$dungeonId'
      path: '/$worldId/$dungeonId'
      fullPath: '/app/journey/$worldId/$dungeonId'
      preLoaderRoute: typeof AppJourneyWorldIdDungeonIdRouteImport
      parentRoute: typeof AppJourneyRoute
    }
    '/app/admin/students/$id': {
      id: '/app/admin/students/$id'
      path: '/admin/students/$id'
      fullPath: '/app/admin/students/$id'
      preLoaderRoute: typeof AppAdminStudentsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppAnalyticsRouteChildren {
  AppAnalyticsTestIdRoute: typeof AppAnalyticsTestIdRoute
}

const AppAnalyticsRouteChildren: AppAnalyticsRouteChildren = {
  AppAnalyticsTestIdRoute: AppAnalyticsTestIdRoute,
}

const AppAnalyticsRouteWithChildren = AppAnalyticsRoute._addFileChildren(
  AppAnalyticsRouteChildren,
)

interface AppJourneyRouteChildren {
  AppJourneyIndexRoute: typeof AppJourneyIndexRoute
  AppJourneyWorldIdDungeonIdRoute: typeof AppJourneyWorldIdDungeonIdRoute
  AppJourneyWorldIdIndexRoute: typeof AppJourneyWorldIdIndexRoute
}

const AppJourneyRouteChildren: AppJourneyRouteChildren = {
  AppJourneyIndexRoute: AppJourneyIndexRoute,
  AppJourneyWorldIdDungeonIdRoute: AppJourneyWorldIdDungeonIdRoute,
  AppJourneyWorldIdIndexRoute: AppJourneyWorldIdIndexRoute,
}

const AppJourneyRouteWithChildren = AppJourneyRoute._addFileChildren(
  AppJourneyRouteChildren,
)

interface AppPvpRouteChildren {
  AppPvpIndexRoute: typeof AppPvpIndexRoute
  AppPvpBrIdRoute: typeof AppPvpBrIdRoute
  AppPvpDuelIdRoute: typeof AppPvpDuelIdRoute
}

const AppPvpRouteChildren: AppPvpRouteChildren = {
  AppPvpIndexRoute: AppPvpIndexRoute,
  AppPvpBrIdRoute: AppPvpBrIdRoute,
  AppPvpDuelIdRoute: AppPvpDuelIdRoute,
}

const AppPvpRouteWithChildren =
  AppPvpRoute._addFileChildren(AppPvpRouteChildren)

interface AppTestsRouteChildren {
  AppTestsTestIdRoute: typeof AppTestsTestIdRoute
}

const AppTestsRouteChildren: AppTestsRouteChildren = {
  AppTestsTestIdRoute: AppTestsTestIdRoute,
}

const AppTestsRouteWithChildren = AppTestsRoute._addFileChildren(
  AppTestsRouteChildren,
)

interface AppRouteChildren {
  AppAchievementsRoute: typeof AppAchievementsRoute
  AppAnalyticsRoute: typeof AppAnalyticsRouteWithChildren
  AppAnnouncementsRoute: typeof AppAnnouncementsRoute
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppCoinsRoute: typeof AppCoinsRoute
  AppCollectionRoute: typeof AppCollectionRoute
  AppContentRoute: typeof AppContentRoute
  AppGuidebookRoute: typeof AppGuidebookRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppJourneyRoute: typeof AppJourneyRouteWithChildren
  AppLeaderboardRoute: typeof AppLeaderboardRoute
  AppNotesRoute: typeof AppNotesRoute
  AppPassesRoute: typeof AppPassesRoute
  AppPetsRoute: typeof AppPetsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppPvpRoute: typeof AppPvpRouteWithChildren
  AppReportCardRoute: typeof AppReportCardRoute
  AppResultsRoute: typeof AppResultsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppShopRoute: typeof AppShopRoute
  AppSpinRoute: typeof AppSpinRoute
  AppStudentsRoute: typeof AppStudentsRoute
  AppTalentsRoute: typeof AppTalentsRoute
  AppTestsRoute: typeof AppTestsRouteWithChildren
  AppWelcomeRoute: typeof AppWelcomeRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminAssessmentRoute: typeof AppAdminAssessmentRoute
  AppAdminAttendanceRoute: typeof AppAdminAttendanceRoute
  AppAdminCadetsRoute: typeof AppAdminCadetsRoute
  AppAdminContentRoute: typeof AppAdminContentRoute
  AppAdminDashboardRoute: typeof AppAdminDashboardRoute
  AppAdminGamificationRoute: typeof AppAdminGamificationRoute
  AppAdminLectureQuizzesRoute: typeof AppAdminLectureQuizzesRoute
  AppAdminLectureViewsRoute: typeof AppAdminLectureViewsRoute
  AppAdminLumiRoute: typeof AppAdminLumiRoute
  AppAdminOfflineTestsRoute: typeof AppAdminOfflineTestsRoute
  AppAdminPassesRoute: typeof AppAdminPassesRoute
  AppAdminQuizImportRoute: typeof AppAdminQuizImportRoute
  AppAdminSettingsRoute: typeof AppAdminSettingsRoute
  AppAdminSpinRoute: typeof AppAdminSpinRoute
  AppAdminTalentsRoute: typeof AppAdminTalentsRoute
  AppBuildingMathRoute: typeof AppBuildingMathRoute
  AppAdminStudentsIdRoute: typeof AppAdminStudentsIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAchievementsRoute: AppAchievementsRoute,
  AppAnalyticsRoute: AppAnalyticsRouteWithChildren,
  AppAnnouncementsRoute: AppAnnouncementsRoute,
  AppAttendanceRoute: AppAttendanceRoute,
  AppCoinsRoute: AppCoinsRoute,
  AppCollectionRoute: AppCollectionRoute,
  AppContentRoute: AppContentRoute,
  AppGuidebookRoute: AppGuidebookRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppJourneyRoute: AppJourneyRouteWithChildren,
  AppLeaderboardRoute: AppLeaderboardRoute,
  AppNotesRoute: AppNotesRoute,
  AppPassesRoute: AppPassesRoute,
  AppPetsRoute: AppPetsRoute,
  AppProfileRoute: AppProfileRoute,
  AppPvpRoute: AppPvpRouteWithChildren,
  AppReportCardRoute: AppReportCardRoute,
  AppResultsRoute: AppResultsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppShopRoute: AppShopRoute,
  AppSpinRoute: AppSpinRoute,
  AppStudentsRoute: AppStudentsRoute,
  AppTalentsRoute: AppTalentsRoute,
  AppTestsRoute: AppTestsRouteWithChildren,
  AppWelcomeRoute: AppWelcomeRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminAssessmentRoute: AppAdminAssessmentRoute,
  AppAdminAttendanceRoute: AppAdminAttendanceRoute,
  AppAdminCadetsRoute: AppAdminCadetsRoute,
  AppAdminContentRoute: AppAdminContentRoute,
  AppAdminDashboardRoute: AppAdminDashboardRoute,
  AppAdminGamificationRoute: AppAdminGamificationRoute,
  AppAdminLectureQuizzesRoute: AppAdminLectureQuizzesRoute,
  AppAdminLectureViewsRoute: AppAdminLectureViewsRoute,
  AppAdminLumiRoute: AppAdminLumiRoute,
  AppAdminOfflineTestsRoute: AppAdminOfflineTestsRoute,
  AppAdminPassesRoute: AppAdminPassesRoute,
  AppAdminQuizImportRoute: AppAdminQuizImportRoute,
  AppAdminSettingsRoute: AppAdminSettingsRoute,
  AppAdminSpinRoute: AppAdminSpinRoute,
  AppAdminTalentsRoute: AppAdminTalentsRoute,
  AppBuildingMathRoute: AppBuildingMathRoute,
  AppAdminStudentsIdRoute: AppAdminStudentsIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
